In [70]:
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
import numpy as np

In [71]:
cancer=load_breast_cancer()
x_cancer=cancer.data
y_cancer=cancer.target

In [72]:
x_train,x_test,y_train,y_test=train_test_split(x_cancer,y_cancer)

In [73]:
x_test

array([[1.080e+01, 9.710e+00, 6.877e+01, ..., 4.603e-02, 2.090e-01,
        7.699e-02],
       [8.598e+00, 2.098e+01, 5.466e+01, ..., 2.778e-02, 2.972e-01,
        7.712e-02],
       [1.267e+01, 1.730e+01, 8.125e+01, ..., 5.602e-02, 2.688e-01,
        6.888e-02],
       ...,
       [1.143e+01, 1.731e+01, 7.366e+01, ..., 6.402e-02, 2.584e-01,
        8.096e-02],
       [1.272e+01, 1.767e+01, 8.098e+01, ..., 3.612e-02, 2.165e-01,
        6.025e-02],
       [1.026e+01, 1.658e+01, 6.585e+01, ..., 8.333e-02, 2.691e-01,
        9.479e-02]], shape=(143, 30))

In [74]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)
x_test

array([[-0.98402628, -2.26977799, -0.99683037, ..., -1.09256053,
        -1.28850384, -0.40052696],
       [-1.62200502,  0.38591785, -1.59080673, ..., -1.37347694,
         0.08711772, -0.39310481],
       [-0.4422369 , -0.48124814, -0.4714707 , ..., -0.93878766,
        -0.35582618, -0.86355522],
       ...,
       [-0.80149831, -0.47889171, -0.79098031, ..., -0.81564622,
        -0.51803099, -0.17386578],
       [-0.42775055, -0.39406025, -0.48283665, ..., -1.24510199,
        -1.17152922, -1.3562721 ],
       [-1.14047883, -0.65091105, -1.11975107, ..., -0.51841357,
        -0.3511472 ,  0.61573728]], shape=(143, 30))

In [75]:
classifier=LogisticRegression(max_iter=1000).fit(x_train,y_train)

In [76]:
import pandas as pd
y_pred=classifier.predict(x_test)
print(pd.DataFrame({"Predicted":y_pred,"Actual":y_test}))

     Predicted  Actual
0            1       1
1            1       1
2            1       1
3            0       0
4            1       1
..         ...     ...
138          0       0
139          1       1
140          1       1
141          1       1
142          1       1

[143 rows x 2 columns]


In [77]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report
cm=confusion_matrix(y_test,y_pred)
print(cm,"\n",accuracy_score(y_test,y_pred),"\n",classification_report(y_test,y_pred))

[[47  1]
 [ 0 95]] 
 0.993006993006993 
               precision    recall  f1-score   support

           0       1.00      0.98      0.99        48
           1       0.99      1.00      0.99        95

    accuracy                           0.99       143
   macro avg       0.99      0.99      0.99       143
weighted avg       0.99      0.99      0.99       143



In [78]:
import joblib,pickle
joblib.dump(classifier,"cancer_model.joblib")
with open('cancer_model.pkl','wb') as f:
    pickle.dump(classifier,f)